version: "3.8"

services:
    # Production service (builds static files with Nginx)
    cv-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: new-cv-app
        ports:
            - "8080:80"
        restart: unless-stopped
        networks:
            - cv-network

    # Development service (hot reloading with Vue dev server)
    cv-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: new-cv-dev
        ports:
            - "3000:8080"
        volumes:
            # Mount source code for live changes
            - "./src:/app/src"
            - "./public:/app/public"
            - "./package.json:/app/package.json"
            - "./vue.config.js:/app/vue.config.js"
            - "./babel.config.js:/app/babel.config.js"
            - "./postcss.config.js:/app/postcss.config.js"
            # Exclude node_modules to avoid conflicts
            - "/app/node_modules"
        environment:
            - CHOKIDAR_USEPOLLING=true # Enable file watching in Docker
        restart: unless-stopped
        networks:
            - cv-network

networks:
    cv-network:
        driver: bridge
